### ISSUE TITLE
Split WinMain into separate file; "library-ize" it.

### ISSUE THREAD

**Issue by IngwiePhoenix** [lvgl/lv_port_windows#1]
Hello!

I was honestly awestuck when I saw the implementation here. Before, I had seen people implement LVGL ports for Windows - but usually by either using D3D or OpenGL - or, even worse, via software rendering. This approach here however uses the WinAPI directly, which is perfect!

One thing that I noticed - but, this could also just be the demo - is that the arcs on the second page seem to be stuttering and not move smoothly, although 62 FPS is reported in the bottom right (I use an AMD Ryzen 9 3900X, NVIDIA 2080 TI, 32GB@3200MHz).

That said though, it would be great if we could use this implementation of an "LVGL port" in our own projects too. Since you already did most of the work, I'd love to see `WinMain` moved to it's own file and apropriate header files created instead - allowing one to copy the existing files into their own project and, when using CMake for instance, conditionally use those files in the build process and call the methods accordingly.

One other, small question: Why C++? Other than `reinterpret_cast<T>(V)` there was nothing that would strike me as being "C++ only" - plus, the Win32 API is very much C only. So, why use C++?

Thank you in advance!

Kind regards,
Ingwie

**Comment by MouriNaruto** [comment]
> So, why use C++?

For implementing the accessibility support for Windows, I need to use Microsoft Active Accessibility at least, or use Microsoft UI Automations and implement more complex support, everyone knows that it needs to implement the COM interface. So, it's wise for us to use C++.

> Before, I had seen people implement LVGL ports for Windows - but usually by either using D3D or OpenGL - or, even worse, via software rendering

Today's LVGL only supports software rendering, so it can't improve a lot even you use Direct3D and Vulkan. So I uses Windows GDI bitmap to manage the framebuffer the LVGL generated.

> the arcs on the second page seem to be stuttering and not move smoothly, although 62 FPS is reported in the bottom right

I will try my best to improve that more. But I don't think I can improve it a lot more. May LVGL adds the custom drawing support in the future, I can use GDI and Direct2D to improve that a lot (So this is the another reason that why use C++.), and make it utilize the GPU more and reduce the CPU overhead.

**Comment by MouriNaruto** [comment]
> That said though, it would be great if we could use this implementation of an "LVGL port" in our own projects too. Since you already did most of the work, I'd love to see WinMain moved to it's own file and apropriate header files created instead - allowing one to copy the existing files into their own project and, when using CMake for instance, conditionally use those files in the build process and call the methods accordingly.

I will do more work about that. I need to tidy these implementations before I split it and make it more modularize.

**Comment by MouriNaruto** [comment]
It's not stale. We need track it for long time.
