### ISSUE TITLE
Add filesystem driver from this Other Repo !!

### ISSUE THREAD

**Issue by frak0d** [lvgl/lv_port_windows#2]
Please add the filesystem driver from here :-

https://github.com/Ryzee119/lvgl-sdl/tree/master/lv_drv

Idk how LVGL codebase works internally, do I just need to copy the driver to lv_drv folder ?

**Comment by MouriNaruto** [comment]
Got it.

I am trying to implement the improved LVGL filesystem driver implementation with pure Win32 API. You can know the reason in https://github.com/lvgl/lv_fs_if/issues/15.

The first commit is trying to translate the error code to LVGL filesystem driver error code more precisely. 
https://github.com/lvgl/lv_sim_visual_studio/commit/14eb32129071623b1984e85f8d3d4e6529162731

I will commit the full implementation in the recent days.

Kenji Mouri

**Comment by MouriNaruto** [comment]
Because this repo (`lv_port_windows`) is designed for developers to develop Windows desktop application with LVGL. So this repo's implementation will add more helper functions about that. (For example, the way to interop with Windows resource APIs.)

**Comment by MouriNaruto** [comment]
The filesystem driver implementation based on Win32 API has been merged in https://github.com/lvgl/lvgl/pull/2701.

So I close the issue.

Kenji Mouri
