### ISSUE TITLE
Is lv_port_windows production ready?

### ISSUE THREAD

**Issue by escherstair** [lvgl/lv_port_windows#4]
I see in the roadmap that there are some items not completed yet, and so I wonder if this porting to Windows is "production ready" or in a beta stage.
Moreover, is it possible using it with VSCode and a modern supported toolchain (i.e. MinGW)?

Thanks

**Comment by MouriNaruto** [comment]
This project is in the beta stage. There are many things need to implement.

Currently, you can't use it with VSCode and MinGW. But I will consider your suggestion.

Kenji Mouri

**Comment by escherstair** [comment]
Let me know if I can help somehow.
Not sure if I can do many things.
